version: '3'
services: 
    web:
        container_name: nginx1
        ports: 
            - "8081:80"
        image: nginx
        networks:
            - net-test1
    web2:
        container_name: nginx2
        ports: 
            - "8082:80"
        image: nginx
        networks:
            - net-test1
#volumes: 
networks:
    net-test1: